const products={p1:{title:'Terracotta Cabin Chunky Throw',category:'Blankets',price:'$145.00',image:'assets/throw.jpg',description:'A rich, textured chunky crochet throw in earthy terracotta and toasted cream.',size:'52 x 64 in throw size',materials:'100% ethically sourced Peruvian Highland Wool',care:'Hand wash cold and lay flat to dry.'},p2:{title:'Barnaby Sweetheart Teddy Bear',category:'Amigurumi / Toys',price:'$58.00',image:'assets/teddy.jpg',description:'A baby-safe crocheted teddy with a miniature dusty rose heart.',size:'9.5 in seated height',materials:'GOTS cotton and hypoallergenic corn-fiber stuffing',care:'Spot clean or gently machine wash.'},p3:{title:'Meadow Motif Granny Cardigan',category:'Clothing',price:'$185.00',image:'assets/cardigan.jpg',description:'A wearable work of art assembled from floral sunburst granny squares.',size:'XS/S through XL/2XL',materials:'Merino wool and recycled organic cotton blend',care:'Hand wash cool and dry flat.'},p4:{title:'Sage & Jute Botanical Pot Cozy Set',category:'Home Decor',price:'$36.00',image:'assets/pot-cozy.jpg',description:'Tactile plant pot sleeves with matching scalloped coasters.',size:'Fits 4 to 6 in nursery pots',materials:'Unbleached jute and recycled sage cotton',care:'Wipe with a damp cloth.'},p5:{title:'Wildflower Square Market Tote',category:'Accessories',price:'$64.00',image:'assets/tote.jpg',description:'A sturdy granny-square tote with reinforced shoulder straps.',size:'15 x 16 in with 11 in strap drop',materials:'Mercerized heavy cotton yarn',care:'Machine wash cold and dry flat.'},p6:{title:'Fireside Cable Knit Wool Slippers',category:'Accessories',price:'$48.00',image:'assets/slippers.jpg',description:'Cable-knit house slippers with a ribbed collar and cushioned sole.',size:'Women’s US 5-10',materials:'Wool-alpaca blend and felted wool soles',care:'Hand wash cool and reshape while damp.'}};
const $=selector=>document.querySelector(selector);const $$=selector=>document.querySelectorAll(selector);
function validEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function closeMenu(){const menu=$('#nav-links-menu');const toggle=$('#mobile-toggle');menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.innerHTML='<i class="fa-solid fa-bars"></i>'}
function openProduct(id){const item=products[id];if(!item)return;$('#modal-image').src=item.image;$('#modal-image').alt=item.title;$('#modal-category').textContent=item.category;$('#modal-title').textContent=item.title;$('#modal-price').textContent=item.price;$('#modal-description').textContent=item.description;$('#modal-size').textContent=item.size;$('#modal-materials').textContent=item.materials;$('#modal-care').textContent=item.care;const modal=$('#product-modal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#modal-close').focus()}
function closeProduct(){const modal=$('#product-modal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.addEventListener('DOMContentLoaded',()=>{
  $('#current-year').textContent=new Date().getFullYear();
  const nav=$('#main-nav');window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>20),{passive:true});
  $('#mobile-toggle').addEventListener('click',()=>{const menu=$('#nav-links-menu');const open=menu.classList.toggle('open');$('#mobile-toggle').setAttribute('aria-expanded',String(open));$('#mobile-toggle').innerHTML=open?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>'});
  $$('#nav-links-menu a').forEach(link=>link.addEventListener('click',closeMenu));
  const sections=$$('main section[id]');const navLinks=$$('.nav-link');const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}),{rootMargin:'-20% 0px -70%'});sections.forEach(section=>sectionObserver.observe(section));
  const revealItems=$$('.section-heading,.about-image-wrap,.about-content,.newsletter-card,.contact-copy,.contact-form');revealItems.forEach(item=>item.classList.add('reveal'));const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{rootMargin:'0px 0px -10%'});revealItems.forEach(item=>revealObserver.observe(item));
  $$('.filter-btn').forEach(button=>button.addEventListener('click',()=>{$$('.filter-btn').forEach(item=>{item.classList.remove('active');item.setAttribute('aria-selected','false')});button.classList.add('active');button.setAttribute('aria-selected','true');$$('.product-card').forEach(card=>card.classList.toggle('hidden',button.dataset.category!=='all'&&card.dataset.category!==button.dataset.category))}));
  $$('.product-card').forEach(card=>{card.addEventListener('click',()=>openProduct(card.dataset.id));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openProduct(card.dataset.id)}})});
  $('#modal-close').addEventListener('click',closeProduct);$('#product-modal').addEventListener('click',event=>{if(event.target.id==='product-modal')closeProduct()});window.addEventListener('keydown',event=>{if(event.key==='Escape')closeProduct()});$('#modal-order').addEventListener('click',()=>{const title=$('#modal-title').textContent;closeProduct();$('#contact-message').value=`Hi Clara, I am interested in ordering the "${title}". Could you please share current turnaround times and custom options?`});
  $('#newsletter-form').addEventListener('submit',event=>{event.preventDefault();const input=$('#newsletter-email');const feedback=$('#newsletter-feedback');if(validEmail(input.value.trim())){input.value='';feedback.textContent='Thank you! You are subscribed to the Yarn Circle.';feedback.classList.add('show')}});
  $('#contact-form').addEventListener('submit',event=>{event.preventDefault();const fields=[['contact-name','name-error',value=>value.trim().length>0],['contact-email','email-error',validEmail],['contact-message','message-error',value=>value.trim().length>=10]];let valid=true;fields.forEach(([inputId,errorId,check])=>{const input=$(`#${inputId}`);const error=$(`#${errorId}`);const good=check(input.value);input.classList.toggle('input-error',!good);error.classList.toggle('show',!good);if(!good)valid=false});const feedback=$('#contact-feedback');if(valid){event.target.reset();feedback.textContent='Thank you! Clara will reply to your email shortly.';feedback.classList.add('show')}});
});
